apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Test-vj
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/snps-pvijaya
    path: /backstage-catalog
    targetRevision: HEAD
  destination: 
    name: docker-desktop
    namespace: default